GET http://localhost:8080/employee
Content-Type: application/json

###

POST http://localhost:8080/employee
Content-Type: application/json

{
  "name": "bot",
  "email": "bot@gmail.com",
  "salary": 20500000
}

###

DELETE http://localhost:8080/employee/3
Content-Type: application/json

### 

PUT http://localhost:8080/employee/4
Content-Type: application/json

{
  "name": "anonymous",
  "email": "anonymous@gmail.com",
  "salary": 12000000
}