GET http://localhost:8080/employee
Content-Type: application/json

###

POST http://localhost:8080/employee
Content-Type: application/json

{
  "name": "itsuki nakano",
  "email": "nakanoitsuki@gmail.com",
  "salary": 20500000
}

###

DELETE http://localhost:8080/employee/3
Content-Type: application/json